In [1]:
import pandas as pd
import numpy as np
import itertools as it


import networkx as nx
import netstats as ns


import spacy
#import contextualSpellCheck

from gensim.models import KeyedVectors
from gensim.models import FastText
import umap
import hdbscan

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
nlp = spacy.load('en_core_web_trf')
# contextualSpellCheck.add_to_pipe(nlp) # use context to correct spelling

In [115]:
# cleaned_data
df = pd.read_csv('partial_cleaned.txt', sep='\t')
print(len(df))

4270

In [4]:
text_qs = ['V161069', # PRE: Text- What is it that R likes about Democratic Pres cand
           'V161072', # PRE: Text- What is it that R dislikes about Democratic Pres cand
           'V161075', # PRE: Text- What is it that R likes about Republican Pres cand
           'V161078', # PRE: Text- What is it that R dislikes about Republican Pres cand
           'V161098', # PRE: Text- What does R like about Democratic party
           'V161101', # PRE: Text- What does R dislike about the Democratic party
           'V161104', # PRE: Text- What does R like about Republican party
           'V161106'  # PRE: Text- What does R dislike about the Republican party
          ]

politics = ['leftright', # 0=strong Dem, 6 = strong Rep
            'politicalinterest', # 0 = not at all interested, 3= v interested
            'politicalparticipation', # 0 = no protest or petition, 1 = one activity, 2 = both activities
           ]

personality = [
               'TIPI_extraversion',
               'TIPI_agreeableness', 
               'TIPI_conscientiousness',
               'TIPI_emotionalstability', 
               'TIPI_openness'
              ]

demographics = ['age', 
                'female', 
                'education']

# to be calculated for each text q
stats = ['clustering',
         'giant component',
         'disssortativity',
         'k avg',
         'k std',
         'entropy',
         'density']

In [5]:
# rescale politics
pids = {0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 2, 6: 2, '': np.nan}
    
df['party_id'] = df['leftright'].fillna('').apply(lambda x: pids[x])

In [6]:
for q in text_qs:
    sub = df.dropna(subset=q)
    print(q, f'{len(sub)} respondents')

V161069 1936 respondents
V161072 2599 respondents
V161075 1849 respondents
V161078 2909 respondents
V161098 2046 respondents
V161101 2297 respondents
V161104 1947 respondents
V161106 2531 respondents

In [119]:
# Summary statistics
sub = df[['V160001'] + text_qs]

In [120]:
sub.head()

,V160001,V161069,V161072,V161075,V161078,V161098,V161101,V161104,V161106
0,1,NaN,everything,truth//his caring for the country,NaN,NaN,i see them trying take to much and give to the...,more straightforward and for the people,NaN
1,2,NaN,seem corptupt anti gun anti 2nd amen,pro 2nd amendement//,erassional//,NaN,NaN,pro 2nd ament small gov oppose gov envolement//,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,whole personal//no,he says what he thinks//I believe he will do w...,arganize,NaN,their stand on health care//pro life//taxxes//...,their stand on health care issue//pro life iss...,lack of unity//
4,5,NaN,Im not really strong on their policies and tha...,NaN,dont feel he has political experience//,they tend to try to work for the poor people//,NaN,usually go with morals and try to get people t...,NaN

In [128]:
df = sub.melt(id_vars='V160001', 
              value_vars=text_qs, 
              var_name='question',
              value_name='response')

df = df.rename(columns={'V160001':'id'})

In [142]:
df['word_count'] = df['response'].apply(lambda x: len(str(x).split()) if x==x else np.nan)
print(np.mean(df['word_count'].dropna()))
print(np.std(df['word_count'].dropna()))
print(max(df['word_count'].dropna()))

9.413878767803908
13.959977950196683
204.0

In [147]:
counts = df[['id', 'response']].groupby('id').count()

In [148]:
np.mean(counts)

4.2421545667447305

In [150]:
np.max(counts)

8

In [161]:
len([val for val in counts['response'] if val > 1])

3845

# Text pre-processing

In [7]:
# replace original answers with cleaned _doc answers
for q in text_qs:
    df[q] = df[f'{q}_doc']

In [8]:
# create spacy docs of each response
for q in text_qs:
    print(q)
    df[f'{q}_doc'] = df[q].fillna('').apply(lambda x: nlp(x))

V161069
V161072
V161075
V161078
V161098
V161101
V161104
V161106

In [9]:
df.to_csv('cleaned.txt', sep='\t', index=False)

# Network extraction

## Step 1: identify all terms (nodes) and sentences (for embeddings) across all text responses

In [10]:
# keep as nodes word that are these parts of speech:
keep_pos = ['ADJ','ADV', 'NOUN', 'PROPN', 'VERB']

In [12]:
raw_nodes = set()

for q in text_qs:
    docs = df[f'{q}_doc']

    for doc in docs:
        # nodes to keep (unclustered)
        for token in doc:
            if token.pos_ in keep_pos:
                raw_nodes.add(token.lemma_)

## Step 2: Embeddings and lemmatization

In [13]:
# embeddings model
model = KeyedVectors.load_word2vec_format('~/nltk_data/GoogleNews-vectors-negative300.bin', binary=True)

In [14]:
vecs = list()
kept = list()
skipped = list()

for word in raw_nodes:
    try:
        vector = model[word]
        vecs.append(vector) # save vector
        kept.append(word) # save word
    except:
        skipped.append(word) # out of vocab (after spell check correction)
    
word_embeddings = np.vstack(vecs)

print(word_embeddings.shape)
print(len(skipped))

(6027, 300)
2744

### clustering using UMap + hdbscan

In [15]:
reducer = umap.UMAP(n_components=10) 
embedding = reducer.fit_transform(word_embeddings)

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

In [16]:
clusterer = hdbscan.HDBSCAN(min_cluster_size=2, min_samples=5, prediction_data=True)
cluster_labels = clusterer.fit_predict(embedding)

In [17]:
clust_words = dict() # {num : [words]}

for word, clust in zip(kept, cluster_labels):
    clust_words.setdefault(clust, set())
    clust_words[clust].add(word)
    
    
word_label = dict() # {word : label}

for word, clust in zip(kept, cluster_labels):

    if clust >= 0: # keep clustered words
        word_label[word] = list(clust_words[clust])[0]

In [112]:
clust_words[4]

{'coherent',
 'cohesion',
 'cohesive',
 'cohesiveness',
 'solidarity',
 'togetherness',
 'unification',
 'unified',
 'unify',
 'unite',
 'united',
 'unites',
 'unity'}

## Step 3: Construct Network for each response

In [18]:
def check_negs(nodes, all_edges, neg_parents): 
    neg = nlp('NEG')[0]

    # add 'NEG' as node
    nodes.append(neg) 
        
    # add 'NEG' to edge list
    for p in neg_parents:
        
        # add 'NEG' as key
        all_edges[neg] = p.head
        del all_edges[p] # remove head
        
        # add 'NEG' as value
        for k, v in all_edges.items():
            if v == p:
                all_edges[k] = neg
                
    return nodes, all_edges

In [19]:
def prune_edges(all_edges, nodes):
    edges = list()

    for child, parent in all_edges.items():
        if child in nodes: # if we have a child that is a node
            seen = set()

            while parent not in nodes and parent not in seen: # find a parent
                grand = all_edges[parent]
                seen.add(parent)

                if grand == parent: # if we're in a loop
                    break
                else:
                    parent = grand # iteratively check grand parents

            if child.text != parent.text and parent in nodes:
                edges.append([child, parent])
                
    return edges

In [20]:
def merge_nodes(nodes, edges):
                
    ##### NODES #####
    lemma_nodes = [node.lemma_ for node in nodes]
    final_nodes = set()
    has_neg = False
    
    for node in lemma_nodes:
        # case 1: replace with cluster label
        if node in word_label:
            final_nodes.add(word_label[node])
        # case 2: this is a node indicating negation (drop)
        elif node == 'NEG':
            has_neg = True
        # case 3: this is a node w/ no cluster label (add as is)
        else:
            final_nodes.add(node)
            
    #### EDGES #####
    # step 1: lemmatize & cluster
    clean_edges = list() # allows for duplicated edges
    
    for e1, e2 in edges:
        clean_edge = list()
        
        for e in [e1, e2]:
            lemma = e.lemma_

            if lemma in word_label: # if in cluster
                clean_edge.append(word_label[lemma])
            else:
                clean_edge.append(lemma)
                
        clean_edges.append(clean_edge)    
    
    keep_edges = list() # edges to add/keep

    neg_edge = list() # track pairs

    for e1, e2 in clean_edges:
        keep = True

        if e1=='NEG':
            neg_edge.append(e2)
            keep = False
        elif e2=='NEG':
            neg_edge.append(e1)
            keep = False

        # keep edges with no negation
        if keep:
            keep_edges.append([e1, e2, 1]) # positive weight


        # if we've found two things connected to negatives
        # taking advantage of edges being in order
        if len(neg_edge) == 2:
            neg_edge.append(-1) # negative weight
            keep_edges.append(neg_edge) # add to list of keep edges
            neg_edge = list() # clear
                
        # replace orig edges
        final_edges = keep_edges
        
    return final_nodes, final_edges

In [21]:
def get_network(doc):
    
    all_nodes = set()
    all_edges = list()
    skipped = 0

    for sent in doc.sents:
        try:
            # Step 1: Nodes (words to keep)
            nodes = [token for token in sent if token.pos_ in keep_pos]

            # Step 2: Edges (parse tree)
            ### 2a: all edges
            raw_edges = dict() # child : parent

            for token in sent:
                raw_edges[token] = token.head

            ### 2b: Check negatives
            neg_parents = [token.head for token in sent if token.dep_ == 'neg']

            if len(neg_parents) > 0:
                nodes, raw_edges = check_negs(nodes, raw_edges, neg_parents)

            # 2c: edges to keep
            edges = prune_edges(raw_edges, nodes)

            # Step 3: finalize based on word clusters, negatives
            final_nodes, final_edges = merge_nodes(nodes, edges)
        except:
            final_nodes = list()
            final_edges = list()
            skipped += 1
    
        # update for full doc
        for node in final_nodes:
            all_nodes.add(node)

        for e in final_edges:
            all_edges.append(e)
        
    network = {'nodes' : all_nodes,
               'edges' : all_edges}
    
    #if skipped > 0:
    #    print(f'  {skipped} sentences skipped')
    
    return network

In [22]:
def get_network_stats(network):
    nodes = network['nodes']
    edges = network['edges']
    
    if len(nodes) > 1 and len(edges) > 0:
        G = nx.Graph()
        G.add_weighted_edges_from(edges)

        for node in nodes:
            G.add_node(node)

        stats = ns.network_stats(G)
    
    else:
        stats = dict()
        
    return stats

In [23]:
for q in text_qs:
    print(q)
    
    # get network from response text
    df[f'{q}_network'] = df[f'{q}_doc'].apply(lambda doc: get_network(doc))
    
    # get stats from network
    df[f'{q}_stats'] =  df[f'{q}_network'].apply(lambda network: get_network_stats(network))

V161069
V161072
V161075
V161078
V161098
V161101
V161104
V161106

In [25]:
df.to_csv('network_data.csv', index=False)

In [ ]:
# Reload saved data
df = pd.read_csv('network_data.csv')

# Analysis 1: Network structure + personality
1. Transform all free response text into networks
2. Calculate network statistics for each network
3. Multilevel model: $s = \beta p + \alpha_q + \epsilon$. Captures relationship between personal trait $p$ and network statistic $s$ while controlling for question-level random effects $\alpha_q$.
4. Save t-statistics if signficant -- these are the correlations of interest

Notes: 
* Controlling for questions allows us to have multiple networks (responses) per individual. May need to cluster standard errors, though
* May want to consider word count and flesch-kincaid score?

In [26]:
from pymer4.models import lmer
import polars as pl

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

Error importing in API mode: ImportError("dlopen(/Users/ss4316/.pyenv/versions/3.10.6/lib/python3.10/site-packages/_rinterface_cffi_api.abi3.so, 0x0002): Library not loaded: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib\n  Referenced from: <2EEBEE81-EBFD-3117-97B1-20AFEEB66792> /Users/ss4316/.pyenv/versions/3.10.6/lib/python3.10/site-packages/_rinterface_cffi_api.abi3.so\n  Reason: tried: '/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.dylib' (no such file)")
Trying to import in ABI mode.

### Step 1: reshape data

Each row should be the response to a single question, with [politics, personality, demographics] + [network stats for that answer]

In [27]:
stat_col = [f'{q}_stats' for q in text_qs]

cols = ['V160001'] + politics + personality + demographics
cols

['V160001',
 'leftright',
 'politicalinterest',
 'politicalparticipation',
 'TIPI_extraversion',
 'TIPI_agreeableness',
 'TIPI_conscientiousness',
 'TIPI_emotionalstability',
 'TIPI_openness',
 'age',
 'female',
 'education']

In [28]:
data = df[cols + stat_col].melt(id_vars=cols, value_vars=stat_col, 
                                var_name='question',
                                value_name='net_stats')

# drop rows with no network stats
data = data[data['net_stats'].apply(lambda x: len(x) > 0)]

# unwrap stats
for stat in stats:    
    data[stat] = data['net_stats'].apply(lambda x: x[stat])

In [29]:
data.to_csv('stats.csv', index=False)

In [152]:
data = pd.read_csv('stats.csv')

In [100]:
def get_tvals(measures, stats, data):
    t_matrix = np.zeros((len(measures), len(stats)))
    p_matrix = np.zeros((len(measures), len(stats)))

    for measure_index, net_index in list(it.product(range(len(measures)), range(len(stats)))):
        measure_stat = measures[measure_index]
        net_stat = stats[net_index]

        # create a smaller dataframe

        df = data[['V160001', 'question', measure_stat, net_stat]]
        df = df.rename({measure_stat: 'measure_stat', net_stat: 'net_stat'})

        # run model
        model = lmer('measure_stat ~ net_stat  + (1 | question)', data=df)
        model.fit(no_warnings=True, summarize=False, verbose = False)           

        # get t-vals
        t_val = model.result_fit['t_stat'][1]

        if np.isnan(t_val):
            t_val = 0
            print('Warning: no t_val found for method %s, feature %s.\
                Correlation estimated at 0.')

        t_matrix[measure_index][net_index] = t_val

        # get p-val
        p_val = model.result_fit['p_value'][1]
        p_matrix[measure_index][net_index] = p_val

    corr = pd.DataFrame(t_matrix.T, index=stats, columns=measures)
    p = pd.DataFrame(p_matrix.T, index=stats, columns=measures)

    return corr, p

In [48]:
# columns we'll need later
keep = data[['V160001', 'question']]

# columns to rescale
rescale = politics + personality + demographics + stats

#data = data.set_index('Respondent')
data = data[rescale]

In [49]:
scaled = pd.DataFrame(scaler.fit_transform(data), columns=rescale, index=data.index)
scaled = scaled.reset_index()

data = pd.concat([keep, scaled], axis=1, keys='V160001')
data.columns = data.columns.droplevel()
data = data[['V160001', 'question'] + rescale]

In [101]:
measures = politics + personality + demographics

corr, p = get_tvals(measures, stats, pl.DataFrame(data))

In [102]:
corr.to_csv('corr.txt')
p.to_csv('p_vals.txt')

In [68]:
def get_tvals2(measures, stats, data):
    t_matrix = np.zeros((len(measures), len(stats)))
    p_matrix = np.zeros((len(measures), len(stats)))

    for measure_index, net_index in list(it.product(range(len(measures)), range(len(stats)))):
        measure_stat = measures[measure_index]
        net_stat = stats[net_index]

        # create a smaller dataframe

        df = data[['V160001', 'question', measure_stat, net_stat]]
        df = data.rename({measure_stat: 'measure_stat', net_stat: 'net_stat'})

        # run model
        model = lmer('measure_stat ~ net_stat +  (1 | question)', data=df) # + (1 | V160001)
        model.fit(no_warnings=True, summarize=False, verbose = False)           

        # get t-vals
        t_val = model.result_fit['t_stat'][1]

        if np.isnan(t_val):
            t_val = 0
            print('Warning: no t_val found for method %s, feature %s.\
                Correlation estimated at 0.')

        t_matrix[measure_index][net_index] = t_val

        # get p-val
        p_val = model.result_fit['p_value'][1]
        p_matrix[measure_index][net_index] = p_val

    corr = pd.DataFrame(t_matrix.T, index=stats, columns=measures)

    return corr, p_matrix

In [69]:
corr2, p_matrix = get_tvals2(measures, stats, pl.DataFrame(data))

[6.61160566e-01 8.55215887e-01 2.03464100e-03 9.30646179e-04
 5.31796117e-03 1.14058979e-02 9.62144910e-06]
[1.09852115e-02 2.07775162e-11 4.18688429e-06 3.35482593e-23
 4.04176987e-21 8.20797129e-06 9.58618542e-25]
[3.59319972e-01 1.80461409e-01 4.78927426e-03 3.76636114e-10
 1.01302404e-06 9.98443630e-03 1.15583818e-09]
[5.14317751e-02 7.12936287e-04 7.56191088e-01 8.42948228e-03
 6.21957261e-03 7.82084628e-01 4.67461905e-03]
[6.36445900e-01 1.82412023e-01 3.72636360e-02 1.08012051e-02
 1.11488349e-04 7.24406039e-03 6.67993823e-04]
[0.18945215 0.15328959 0.01580425 0.00147527 0.00031485 0.00229004
 0.01470715]
[0.84914502 0.00828935 0.10408313 0.13042395 0.07226716 0.0602597
 0.08354207]
[1.10717107e-01 7.14446369e-08 1.17258724e-04 2.99993468e-21
 4.13688275e-16 1.40023730e-03 2.56979800e-18]
[0.57281443 0.01034504 0.03559383 0.01598821 0.1811476  0.03083362
 0.05258116]
[5.32177468e-01 1.46100454e-05 6.22292797e-02 6.81207033e-01
 5.20700743e-04 4.33440545e-03 4.45835010e-05]
[3.73899929e-01 6.07192854e-04 7.15586029e-03 2.38388353e-18
 9.56838902e-05 2.04772003e-01 1.22055137e-02]

# Analysis 2: Self-similarity vs ideological similarity

For each respondent:

    * Identify qs which are ideologically aligned v. not (ie: if Dem, likes about Dem cand)
    * Compare similarity of network structure between aligned v. not aligned qs
    * Identify comparison set of users with same ideology
    * Compare similarity of network structure between same qs

In [158]:
text_qs = ['V161069', # PRE: Text- What is it that R likes about Democratic Pres cand
           'V161072', # PRE: Text- What is it that R dislikes about Democratic Pres cand
           'V161075', # PRE: Text- What is it that R likes about Republican Pres cand
           'V161078', # PRE: Text- What is it that R dislikes about Republican Pres cand
           'V161098', # PRE: Text- What does R like about Democratic party
           'V161101', # PRE: Text- What does R dislike about the Democratic party
           'V161104', # PRE: Text- What does R like about Republican party
           'V161106'  # PRE: Text- What does R dislike about the Republican party
          ]

pids = {0: 0, 1: 0, 2: 1, 3: 1, 4: 1, 5: 2, 6: 2, '': np.nan}
    
data['party_id'] = data['leftright'].fillna('').apply(lambda x: pids[x])

In [157]:
data.head()

,V160001,leftright,politicalinterest,politicalparticipation,TIPI_extraversion,TIPI_agreeableness,TIPI_conscientiousness,TIPI_emotionalstability,TIPI_openness,age,...,education,question,net_stats,clustering,giant component,disssortativity,k avg,k std,entropy,density
0,12,2.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,86.0,...,2,V161069_stats,"{'node_count': 10, 'edge_count': 6, 'clusterin...",0.000000,0.300000,0.333333,1.200000,0.632456,0.417400,0.133333
1,13,4.0,3.0,0.5,4.0,5.5,5.5,2.5,5.5,30.0,...,3,V161069_stats,"{'node_count': 11, 'edge_count': 8, 'clusterin...",0.000000,0.181818,-0.000000,1.454545,0.934199,0.520894,0.145455
2,15,0.0,3.0,0.5,7.0,6.5,4.5,3.5,6.5,62.0,...,3,V161069_stats,"{'node_count': 3, 'edge_count': 2, 'clustering...",0.000000,1.000000,1.000000,1.333333,0.577350,0.629337,0.666667
3,17,0.0,3.0,0.5,1.5,4.0,6.5,3.5,4.5,46.0,...,3,V161069_stats,"{'node_count': 14, 'edge_count': 12, 'clusteri...",0.047619,0.857143,0.333333,1.714286,1.382783,0.497614,0.131868
4,19,0.0,2.0,0.5,3.5,6.0,5.5,2.0,5.5,30.0,...,3,V161069_stats,"{'node_count': 10, 'edge_count': 10, 'clusteri...",0.143333,1.000000,0.421801,2.000000,1.247219,0.554809,0.222222